import pictureEdite from "../images/picture-edite.png";

export const projectsData = [
  {
    title: "Picture Edite",
    tags: ["JavaScript", "React", "Context API"],
    tagsExibition: ["JavaScript", "React", "Context API"],
    description: "Visa simplificar edições simples sobrepondo fotos em quantidade, com o intuito de poupar força de trabalho.",
    deployLink: "https://main--picture-edite.netlify.app/",
    repoLink: "https://github.com/isaacmacedof/Picture-Edite",
    imgSrc: pictureEdite,
  },
  {
    title: "Picture Edite",
    tags: ["JavaScript", "React", "Context API"],
    tagsExibition: ["JavaScript", "React", "Context API"],
    description: "Visa simplificar edições simples sobrepondo fotos em quantidade, com o intuito de poupar força de trabalho.",
    deployLink: "https://main--picture-edite.netlify.app/",
    repoLink: "https://github.com/isaacmacedof/Picture-Edite",
    imgSrc: pictureEdite,
  },
  {
    title: "Picture Edite",
    tags: ["JavaScript", "React", "Context API"],
    tagsExibition: ["JavaScript", "React", "Context API"],
    description: "Visa simplificar edições simples sobrepondo fotos em quantidade, com o intuito de poupar força de trabalho.",
    deployLink: "https://main--picture-edite.netlify.app/",
    repoLink: "https://github.com/isaacmacedof/Picture-Edite",
    imgSrc: pictureEdite,
  },
  {
    title: "Picture Edite",
    tags: ["JavaScript", "React", "Context API"],
    tagsExibition: ["JavaScript", "React", "Context API"],
    description: "Visa simplificar edições simples sobrepondo fotos em quantidade, com o intuito de poupar força de trabalho.",
    deployLink: "https://main--picture-edite.netlify.app/",
    repoLink: "https://github.com/isaacmacedof/Picture-Edite",
    imgSrc: pictureEdite,
  },
  {
    title: "Picture Edite",
    tags: ["JavaScript", "React", "Context API"],
    tagsExibition: ["JavaScript", "React", "Context API"],
    description: "Visa simplificar edições simples sobrepondo fotos em quantidade, com o intuito de poupar força de trabalho.",
    deployLink: "https://main--picture-edite.netlify.app/",
    repoLink: "https://github.com/isaacmacedof/Picture-Edite",
    imgSrc: pictureEdite,
  },
  {
    title: "Picture Edite",
    tags: ["JavaScript", "React", "Context API"],
    tagsExibition: ["JavaScript", "React", "Context API"],
    description: "Visa simplificar edições simples sobrepondo fotos em quantidade, com o intuito de poupar força de trabalho.",
    deployLink: "https://main--picture-edite.netlify.app/",
    repoLink: "https://github.com/isaacmacedof/Picture-Edite",
    imgSrc: pictureEdite,
  },
  {
    title: "Picture Edite",
    tags: ["JavaScript", "React", "Context API"],
    tagsExibition: ["JavaScript", "React", "Context API"],
    description: "Visa simplificar edições simples sobrepondo fotos em quantidade, com o intuito de poupar força de trabalho.",
    deployLink: "https://main--picture-edite.netlify.app/",
    repoLink: "https://github.com/isaacmacedof/Picture-Edite",
    imgSrc: pictureEdite,
  },
  {
    title: "Picture Edite",
    tags: ["JavaScript", "React", "Context API"],
    tagsExibition: ["JavaScript", "React", "Context API"],
    description: "Visa simplificar edições simples sobrepondo fotos em quantidade, com o intuito de poupar força de trabalho.",
    deployLink: "https://main--picture-edite.netlify.app/",
    repoLink: "https://github.com/isaacmacedof/Picture-Edite",
    imgSrc: pictureEdite,
  },
]